// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjkkvqxprinrkietbqda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpqa2t2cXhwcmlucmtpZXRicWRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxOTg4ODQsImV4cCI6MjA2OTc3NDg4NH0.nwlqdVf2s8vmLcfdCuyLEDYzcAf9DhKFX38vHYHsxQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});